### ISSUE TITLE
SpecificationNotFound when expanding verified

### ISSUE THREAD

**Issue by jaypantone** [PermutaTriangle/comb_spec_searcher#204]
This was a class running for 8ish hours. I will try to run locally.

```py
[E 200806 17:31:55 hammer:244] 0132_0231
    insertion_partial_col_placements_fusion_isolated
    Looking for recursive combinatorial specification with the strategies:
    Inferral: row and column separation, obstruction transitivity
    Initial: tracked fusion, add assumptions, factor, point insertion, point placement
    Verification: verify atoms, insertion encoding verified, one by one verification, locally factorable verification
    Set 1: partial column placement

    Traceback (most recent call last):
      File "/users/personnel/jay/atrap/repos/handy-scripts/jay/hammer/hammer.py", line 164, in run_work_packet
        spec.expand_verified()
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 130, in expand_verified
        self.expand_verified()
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 129, in expand_verified
        self._expand_verified_comb_classes(verification_packs)
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/specification.py", line 213, in _expand_verified_comb_classes
        comb_class_rules, comb_class_eqv_paths = css._auto_search_rules()
      File "/users/personnel/jay/atrap/repos/comb_spec_searcher/comb_spec_searcher/comb_spec_searcher.py", line 671, in _auto_search_rules
        raise SpecificationNotFound
    comb_spec_searcher.exception.SpecificationNotFound
```

**Comment by jaypantone** [comment]
Unable to replicate. We should add a more descriptive error message to help us next time this happens.
